src/objects/product_comparison_Heroku_Postgres_C__dlm/product_comparison_Heroku_Postgres_C__dlm.object-meta.xml
<CustomObject>
    <mktDataModelAttributes>
        <creationType>Custom</creationType>
        <dataModelTaxonomy>Salesforce_SFDCReferenceModel_0_93</dataModelTaxonomy>
        <dataSpaceName>default</dataSpaceName>
        <isEnabled>true</isEnabled>
        <isSegmentable>true</isSegmentable>
        <isUsedForMetrics>false</isUsedForMetrics>
        <labelOverride>product_comparison Heroku Postgres Compe</labelOverride>
        <masterLabel>product_comparison Heroku Postgres Compe</masterLabel>
        <objectCategory>Salesforce_SFDCReferenceModel_0_93.Profile</objectCategory>
    </mktDataModelAttributes>
</CustomObject>

src/objects/product_comparison_Heroku_Postgres_C__dlm/fields/ai_enabled__c.field-meta.xml
<CustomField>
    <fullName>ai_enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ai_enabled</label>
    <mktDataModelFieldAttributes>
        <definitionCreationType>Custom</definitionCreationType>
        <isDynamicLookup>false</isDynamicLookup>
        <labelOverride>ai_enabled</labelOverride>
        <masterLabel>ai_enabled</masterLabel>
        <usageTag>None</usageTag>
    </mktDataModelFieldAttributes>
    <type>Checkbox</type>
</CustomField>

src/objects/product_comparison_Heroku_Postgres_C__dlm/fields/competitor_company_name__c.field-meta.xml
<CustomField>
    <fullName>competitor_company_name__c</fullName>
    <label>competitor_company_name</label>
    <length>60</length>
    <mktDataModelFieldAttributes>
        <definitionCreationType>Custom</definitionCreationType>
        <isDynamicLookup>false</isDynamicLookup>
        <labelOverride>competitor_company_name</labelOverride>
        <masterLabel>competitor_company_name</masterLabel>
        <usageTag>None</usageTag>
    </mktDataModelFieldAttributes>
    <type>Text</type>
</CustomField>

src/objects/product_comparison_Heroku_Postgres_C__dlm/fields/competitor_price__c.field-meta.xml
<CustomField>
    <fullName>competitor_price__c</fullName>
    <label>competitor_price</label>
    <mktDataModelFieldAttributes>
        <definitionCreationType>Custom</definitionCreationType>
        <isDynamicLookup>false</isDynamicLookup>
        <labelOverride>competitor_price</labelOverride>
        <masterLabel>competitor_price</masterLabel>
        <usageTag>None</usageTag>
    </mktDataModelFieldAttributes>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

src/objects/product_comparison_Heroku_Postgres_C__dlm/fields/competitor_product_name__c.field-meta.xml
<CustomField>
    <fullName>competitor_product_name__c</fullName>
    <label>competitor_product_name</label>
    <length>60</length>
    <mktDataModelFieldAttributes>
        <definitionCreationType>Custom</definitionCreationType>
        <isDynamicLookup>false</isDynamicLookup>
        <labelOverride>competitor_product_name</labelOverride>
        <masterLabel>competitor_product_name</masterLabel>
        <usageTag>None</usageTag>
    </mktDataModelFieldAttributes>
    <type>Text</type>
</CustomField>

src/objects/product_comparison_Heroku_Postgres_C__dlm/fields/deployment_type__c.field-meta.xml
<CustomField>
    <fullName>deployment_type__c</fullName>
    <label>deployment_type</label>
    <length>60</length>
    <mktDataModelFieldAttributes>
        <definitionCreationType>Custom</definitionCreationType>
        <isDynamicLookup>false</isDynamicLookup>
        <labelOverride>deployment_type</labelOverride>
        <masterLabel>deployment_type</masterLabel>
        <usageTag>None</usageTag>
    </mktDataModelFieldAttributes>
    <type>Text</type>
</CustomField>

src/objects/product_comparison_Heroku_Postgres_C__dlm/fields/license_period_months__c.field-meta.xml
<CustomField>
    <fullName>license_period_months__c</fullName>
    <label>license_period_months</label>
    <mktDataModelFieldAttributes>
        <definitionCreationType>Custom</definitionCreationType>
        <isDynamicLookup>false</isDynamicLookup>
        <labelOverride>license_period_months</labelOverride>
        <masterLabel>license_period_months</masterLabel>
        <usageTag>None</usageTag>
    </mktDataModelFieldAttributes>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

src/objects/product_comparison_Heroku_Postgres_C__dlm/fields/no_of_users__c.field-meta.xml
<CustomField>
    <fullName>no_of_users__c</fullName>
    <label>no_of_users</label>
    <mktDataModelFieldAttributes>
        <definitionCreationType>Custom</definitionCreationType>
        <isDynamicLookup>false</isDynamicLookup>
        <labelOverride>no_of_users</labelOverride>
        <masterLabel>no_of_users</masterLabel>
        <usageTag>None</usageTag>
    </mktDataModelFieldAttributes>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

src/objects/product_comparison_Heroku_Postgres_C__dlm/fields/product_code__c.field-meta.xml
<CustomField>
    <fullName>product_code__c</fullName>
    <label>product_code</label>
    <length>60</length>
    <mktDataModelFieldAttributes>
        <definitionCreationType>Custom</definitionCreationType>
        <isDynamicLookup>false</isDynamicLookup>
        <labelOverride>product_code</labelOverride>
        <masterLabel>product_code</masterLabel>
        <usageTag>None</usageTag>
    </mktDataModelFieldAttributes>
    <type>Text</type>
</CustomField>

src/objects/product_comparison_Heroku_Postgres_C__dlm/fields/product_name__c.field-meta.xml
<CustomField>
    <fullName>product_name__c</fullName>
    <label>product_name</label>
    <length>60</length>
    <mktDataModelFieldAttributes>
        <definitionCreationType>Custom</definitionCreationType>
        <isDynamicLookup>false</isDynamicLookup>
        <labelOverride>product_name</labelOverride>
        <masterLabel>product_name</masterLabel>
        <usageTag>None</usageTag>
    </mktDataModelFieldAttributes>
    <type>Text</type>
</CustomField>

src/objects/product_comparison_Heroku_Postgres_C__dlm/fields/support_type__c.field-meta.xml
<CustomField>
    <fullName>support_type__c</fullName>
    <label>support_type</label>
    <length>60</length>
    <mktDataModelFieldAttributes>
        <definitionCreationType>Custom</definitionCreationType>
        <isDynamicLookup>false</isDynamicLookup>
        <labelOverride>support_type</labelOverride>
        <masterLabel>support_type</masterLabel>
        <usageTag>None</usageTag>
    </mktDataModelFieldAttributes>
    <type>Text</type>
</CustomField>

src/objects/product_comparison_Heroku_Postgres_C__dlm/fields/supported_devices__c.field-meta.xml
<CustomField>
    <fullName>supported_devices__c</fullName>
    <label>supported_devices</label>
    <length>60</length>
    <mktDataModelFieldAttributes>
        <definitionCreationType>Custom</definitionCreationType>
        <isDynamicLookup>false</isDynamicLookup>
        <labelOverride>supported_devices</labelOverride>
        <masterLabel>supported_devices</masterLabel>
        <usageTag>None</usageTag>
    </mktDataModelFieldAttributes>
    <type>Text</type>
</CustomField>

src/classes/CompetitorInsightsInvokable.cls
/**
 * @description Invokable Apex class to retrieve competitor insights based on Quote Line Item Attributes
 * @author Generated on 2025-04-25
 */
public with sharing class CompetitorInsightsInvokable {
    
    /**
     * @description Wrapper class to hold the request parameters
     */
    public class CompetitorInsightsRequest {
        @InvocableVariable(label='Quote ID' required=true description='ID of the Quote to retrieve competitor insights for')
        public Id quoteId;
    }
    
    /**
     * @description Wrapper class to hold the response
     */
    public class CompetitorInsightsResponse {
        @InvocableVariable(label='Competitor Insights' description='List of competitor insights matching the product and attributes')
        public List<product_comparison_Heroku_Postgres_C__dlm> competitorInsights;
    }
    
    /**
     * @description Invocable method to find competitor insights based on quote line items
     * @param requests List of CompetitorInsightsRequest
     * @return List of CompetitorInsightsResponse
     */
    @InvocableMethod(label='Get Competitor Insights' description='Retrieves competitor insights based on quote line item attributes')
    public static List<CompetitorInsightsResponse> getCompetitorInsights(List<CompetitorInsightsRequest> requests) {
        List<CompetitorInsightsResponse> responses = new List<CompetitorInsightsResponse>();
        
        for (CompetitorInsightsRequest request : requests) {
            CompetitorInsightsResponse response = new CompetitorInsightsResponse();
            response.competitorInsights = findMatchingCompetitorInsights(request.quoteId);
            responses.add(response);
        }
        
        return responses;
    }
    
    /**
     * @description Helper method to find matching competitor insights
     * @param quoteId The ID of the quote
     * @return List of matching competitor insights
     */
    public static List<product_comparison_Heroku_Postgres_C__dlm> findMatchingCompetitorInsights(Id quoteId) {
        // Map to store the attribute values for each quote line item
        Map<Id, Map<String, String>> quoteLineAttributesMap = new Map<Id, Map<String, String>>();
        
        // First, get all quote line items for the quote
        List<QuoteLineItem> quoteLineItems = [
            SELECT Id, Product2Id, Product2.Name, QuoteId
            FROM QuoteLineItem
            WHERE QuoteId = :quoteId
        ];
        
        if (quoteLineItems.isEmpty()) {
            return new List<product_comparison_Heroku_Postgres_C__dlm>();
        }
        
        // Get all quote line item IDs
        Set<Id> quoteLineItemIds = new Set<Id>();
        Map<Id, String> productNameMap = new Map<Id, String>();
        
        for (QuoteLineItem qli : quoteLineItems) {
            quoteLineItemIds.add(qli.Id);
            productNameMap.put(qli.Id, qli.Product2.Name);
            quoteLineAttributesMap.put(qli.Id, new Map<String, String>());
        }
        
        // Query for all attribute values for these quote line items
        List<QuoteLineItemAttribute> attributes = [
            SELECT Id, QuoteLineItemId, AttributeName, AttributeValue
            FROM QuoteLineItemAttribute
            WHERE QuoteLineItemId IN :quoteLineItemIds
            AND AttributeName IN ('AI Enabled', 'License Period', 'Supported Devices', 'Support Type', 'Deployment Type','Number of Users')
        ];
        
        // Map the attribute field names to the product_comparison_Heroku_Postgres_C__dlm field names
        Map<String, String> attributeToFieldMap = new Map<String, String>{
            'AI Enabled' => 'ai_enabled__c',
            'License Period' => 'license_period_months__c',
            'Supported Devices' => 'supported_devices__c',
            'Support Type' => 'support_type__c',
            'Deployment Type' => 'deployment_type__c',
            'Number of Users' => 'no_of_users__c'
        };
        
        // Organize the attributes by quote line item
        for (QuoteLineItemAttribute attr : attributes) {
            Map<String, String> attrMap = quoteLineAttributesMap.get(attr.QuoteLineItemId);
            String fieldName = attributeToFieldMap.get(attr.AttributeName);
            if (fieldName != null && attrMap != null) {
                attrMap.put(fieldName, attr.AttributeValue);
            }
        }
        
        // Now find matching competitor insights for each quote line item
        List<product_comparison_Heroku_Postgres_C__dlm> allMatchingInsights = new List<product_comparison_Heroku_Postgres_C__dlm>();
        
        for (Id quoteLineId : quoteLineAttributesMap.keySet()) {
            String productName = productNameMap.get(quoteLineId);
            Map<String, String> attrValues = quoteLineAttributesMap.get(quoteLineId);
            
            // Build dynamic SOQL query for each quote line item
            String query = 'select Id, ai_enabled__c, competitor_company_name__c, competitor_product_name__c, '+
                          'competitor_price__c, product_name__c, no_of_users__c, deployment_type__c,' + 
                          'license_period_months__c, supported_devices__c, support_type__c, product_code__c ' + 
                          'FROM product_comparison_Heroku_Postgres_C__dlm ' +
                           'WHERE product_name__c = :productName';
            
            // Add attribute filters if they have values
            List<String> conditions = new List<String>();
            Map<String, Object> queryParams = new Map<String, Object>{
                'productName' => productName
            };
            
            // Add conditions for each attribute that has a value
            for (String fieldName : attrValues.keySet()) {
            String value = attrValues.get(fieldName);
            if (String.isNotBlank(value)) {
                String paramName = fieldName.replace('__c', '').toLowerCase();
                Object typedValue = value; // default as String
                System.debug('field => '+fieldName);
                if (fieldName == 'ai_enabled__c') {
                    try {
                        typedValue = Boolean.valueOf(value);
                    } catch (Exception e) {
                        continue;
                    }
                } else if (fieldName == 'license_period_months__c' || fieldName == 'no_of_users__c') {
                    try {
                        typedValue = Decimal.valueOf(value);
                    } catch (Exception e) {
                        continue;
                    }
                }
        
                conditions.add(fieldName + ' = :' + paramName);
                queryParams.put(paramName, typedValue);
            }
        }

        
            // Execute the query
            if (!queryParams.isEmpty()) {
                String finalQuery = query + (conditions.isEmpty() ? '' : ' AND ' + String.join(conditions, ' AND '));
                System.debug('SOQL Query Template: ' + finalQuery);
                System.debug('Query Bind Parameters: ' + queryParams);
                String simulatedQuery = finalQuery;
                for (String key : queryParams.keySet()) {
                    Object paramValue = queryParams.get(key);
                    String replacement;
                
                    if (paramValue instanceof String) {
                        replacement = '\'' + ((String)paramValue).replaceAll('\'', '\\\'') + '\'';
                    } else if (paramValue instanceof Boolean || paramValue instanceof Decimal || paramValue instanceof Integer) {
                        replacement = String.valueOf(paramValue);
                    } else {
                        replacement = '\'' + String.valueOf(paramValue).replaceAll('\'', '\\\'') + '\'';
                    }
                
                    simulatedQuery = simulatedQuery.replace(':' + key, replacement);
                }

                System.debug('Simulated SOQL Query (Approximate): ' + simulatedQuery);


                List<product_comparison_Heroku_Postgres_C__dlm> matchingInsights = Database.queryWithBinds(
                    query + (conditions.isEmpty() ? '' : ' AND ' + String.join(conditions, ' AND ')),
                    queryParams,
                    AccessLevel.USER_MODE
                );
                
                allMatchingInsights.addAll(matchingInsights);
            }
        }
        
        return allMatchingInsights;
    }
}